### ISSUE TITLE
[FR] Implement keybinding callbacks

### ISSUE THREAD

**Issue by DhruvaSambrani** [ronisbr/TerminalPager.jl#18]
I would like to do some other computations when the user moves or triggers other keybindings. Is it possible to expose the pager events so as to customize them?

**Comment by ronisbr** [comment]
Hi @DhruvaSambrani 

Can you please describe better what kind of computations do you want to perform? It should be easy to provide a callback, but I am not sure what kind of modifications in pager you want.

**Comment by DhruvaSambrani** [comment]
I wanted to build a 2D map scroller which would have a player character at the center and the map elements in ASCII. However, for the player to interact with map elements, I would need a way to check if there are any interactable elements at the present location, which would need to be called everytime the pager updates.

**Comment by ronisbr** [comment]
Hum, I think this will not work, because TerminalPager assumes the content does not change after the initialization.

I think this kind of application is not suitable for TerminalPager, which we need to keep as small as possible to avoid overhead to packages that will use it. However, it is a very good application for [TerminalUserInterfaces.jl](https://github.com/ronisbr/TerminalUserInterfaces.jl). The only problem is that I did not have time yet to stabilize the API...

**Comment by DhruvaSambrani** [comment]
Yeah, I thought so too. Awesome work nonetheless!!

**Comment by ronisbr** [comment]
Thanks! I will try to put some effort into TextUserInterfaces to have at least a stable API. Ah! BTW, by stable API I mean a Julian way to create TUI. If you want to uses raw ncurses functions, it should be working fine.
